version: "3.8"

services:
  web:    # Correção na identação para indicar que 'web' é um serviço
    image: nginx:latest
    ports:
      - "8080:80"
  db:     # Correção na identação para indicar que 'db' é um serviço
    image: postgres
    environment:   # Correção na indentação do campo 'environment'
      POSTGRES_PASSWORD: example